### ISSUE TITLE
[Epic] fdk-reasoning-service lytter til, og produserer, Kafka-meldinger

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-reasoning-service#152]
# fdk-reasoning-service lytter til, og produserer, Kafka-meldinger

Disse fire må løses først:
- [x] #157
- [x] #158
- [x] #167 
- [x] #159

---
- [x] #160
  - `CONCEPT_HARVESTED` fra topic `concept-events`
  - `DATA_SERVICE_HARVESTED` fra topic `data-service-events`
  - `DATASET_HARVESTED` fra topic `dataset-events`
  - `EVENT_HARVESTED` fra topic `event-events`
  - `INFORMATION_MODEL_HARVESTED` fra topic `information-model-events`
  - `SERVICE_HARVESTED` fra topic `service-events`
- [x] #161
- [x] #162
  - `CONCEPT_REASONED` til topic `concept-events`
  - `DATA_SERVICE_REASONED` til topic `data-service-events`
  - `DATASET_REASONED` til topic `dataset-events`
  - `EVENT_REASONED` til topic `event-events`
  - `INFORMATION_MODEL_REASONED` til topic `information-model-events`
  - `SERVICE_REASONED` til topic `service-events`

- [x] https://github.com/Informasjonsforvaltning/fdk-kafka-event-publisher/issues/103
  - `fdk-reasoning-service` trenger ikke jobbe seg gjennom hele lista med `*_HARVESTED`-medlinger, men må ta opp tråden der fdk-kafka-event-publisher avslutter
- [x] #164

**Comment by terjesyl** [comment]
ferdigstilt
