### ISSUE TITLE
Refaktorer tester, for mindre duplisering av tripler i input-rdf til testene

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-reasoning-service#170]
Nå er det mye dupliserte RDF-data som input-data til testene. For eksempel gjentas veldig mye av en datasettbeskrivelse, selv om testen som bruker filen tester kun et eller noen få felter.

Kan potensielt refaktoreres til å ha en baseline-beskrivelse for hver type (datasett, begrep), og at triplene som testes for i hver enkelt test defineres i en egen fil. I testen tar man da unionen av disse grafene og kjører testen.

**Comment by terjesyl** [comment]
@NilsOveTen kan vi si at denne er løst, eller er det noen flere forbedringer vi ser? Jeg kan beskrive dem i issuet i så fall.

**Comment by NilsOveTen** [comment]
jeg gjør et forsøk på en litt mer dynamisk måte på å endre input til testene på i det jeg jobber med nå, hvis det fungerer kan vi se nærmere på om det er noen av testene vi kunne refaktorert
