### ISSUE TITLE
Gjentagende feilmelding på reasoning-service, relatert til dataservice/dataset

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-reasoning-service#47]
Ser kun ut til å gjelde en håndfull dataservices fra vegvesen

> java.lang.Exception: null
> 	at no.fdk.fdk_reasoning_service.service.UtilsKt.extractFDKIdAndRecordURI(Utils.kt:270)
> 	at no.fdk.fdk_reasoning_service.service.DatasetService.extractDataset(DatasetService.kt:111)
> 	at no.fdk.fdk_reasoning_service.service.DatasetService.extractCatalog(DatasetService.kt:74)
> 	at no.fdk.fdk_reasoning_service.service.DatasetService.splitDatasetCatalogsFromRDF(DatasetService.kt:66)
> 	at no.fdk.fdk_reasoning_service.service.DatasetService.separateAndSaveDatasets(DatasetService.kt:52)
> 	at no.fdk.fdk_reasoning_service.service.DatasetService.reasonHarvestedDatasets(DatasetService.kt:42)
> 	at no.fdk.fdk_reasoning_service.service.ReasoningActivity$launchReasoning$catalogReasoning$1.invokeSuspend(ReasoningActivity.kt:64)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> Unable to find record for https://dataut.vegvesen.no/dataservice/c8053d37-841f-4958-84e7-3d928130871b

**Comment by NilsOveTen** [comment]
De har lagt til `dcat:DataService` som `dcat:dataset` i ene katalogen. Høsterene filtrerer ut det som har feil type, reasoning-service gjør ikke det og ender opp med denne feilen. Jeg legger til en liten fiks i reasoning-service som filtrerer ut alt som ikke har `rdf:type` lik `dcat:Dataset` når den jobber med datasett

**Comment by NilsOveTen** [comment]
> Jeg legger til en liten fiks i reasoning-service som filtrerer ut alt som ikke har `rdf:type` lik `dcat:Dataset` når den jobber med datasett

Og lignenede for de andre
