### ISSUE TITLE
tema i tjenestekatalogen skal utvides med los-tema ut fra eu data-themes

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-reasoning-service#67]
akkurat som blir gjort for datasett

**Comment by terjesyl** [comment]
Må avklares med Kurt Stian, issue-beskrivelse må oppdateres.

**Comment by NilsOveTen** [comment]
> @KurtStian og @terjesyl fikk dere avklart dette?

Denne ble bare satt på vent, @KurtStian er på saken.

Problemet er at det er en veldig stor mengde potensielle tema som speccen sier skal støttes. Enten reduseres scopet på tema som fdk støtter, eller så må vi endre litt i hvordan vi håndterer dette vha reference-data.

Jeg flytter denne til blocked

**Comment by KurtStian** [comment]
@NilsOveTen Hvordan er dette løst for datasett?: https://informasjonsforvaltning.github.io/dcat-ap-no/#Skal-brukes-for-theme

Ser at kun Data theme er brukt i registreringsløsningen, men er løsningen satt opp til takle alle temaene i EuroVoc ved høsting?
Vil nedlasting av EuroVoc slik at vi har en kopi av denne "tilgjengelig" gjøre dette enklere?

**Comment by NilsOveTen** [comment]
> @NilsOveTen Hvordan er dette løst for datasett?: https://informasjonsforvaltning.github.io/dcat-ap-no/#Skal-brukes-for-theme
> 
> Ser at kun Data theme er brukt i registreringsløsningen, men er løsningen satt opp til takle alle temaene i EuroVoc ved høsting? Vil nedlasting av EuroVoc slik at vi har en kopi av denne "tilgjengelig" gjøre dette enklere?

Hvis noe annet enn Data Theme eller Los blir lagt til så tar vi det med som uri, men ignorerer det ellers. Så en reell eurovoc-uri vil bli håndtert på samme måte som om du la til `https://tull-og-test.com` elns

**Comment by KurtStian** [comment]
Vi ønsker at FDK håndterer hele EuroVoc, og da med koblingene mellom nivåene slik at hvis man f.eks. filtrerer på nivå 1 så skal man også få med ev. tjenester som bruker vokabular fra lavere nivå. (slik som det ser ut som bruken av los fungerer i dag)

EuroVoc brukes også i dcat, men det ser ut som dette ikke er implementert i FDK.

**Comment by KjerstiSteien** [comment]
@NilsOveTen @KurtStian er denne fortsatt på vent, eller kandidat til å ta inn igjen i en sprint?

**Comment by NilsOveTen** [comment]
Dette issuet ble sannsynligvis løst av #76 

Men vi bør sikkert gjøre litt i rdf-parser, kan du @KurtStian få til noe høsting av et datasett og en tjeneste som har eurovoc-tema i staging? Så kan vi se hvordan det går

**Comment by KurtStian** [comment]
@NilsOveTen  Her er to eksempler på staging:
Tjeneste: https://staging.fellesdatakatalog.digdir.no/public-services/309d00a5-1887-314b-a609-a639905c3ab9
Datasett: https://staging.fellesdatakatalog.digdir.no/datasets/7c5a0af9-e275-3d85-9871-5495f42530d8

Vises ikke noe på detaljesiden.

**Comment by NilsOveTen** [comment]
Har lagd disse 3: #79, #80 og https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/247

Det skal være alt som skal til for datasett, kanskje også tjenester. Kan være vi må gjøre litt i portal for å det opp i tjenester, det har jeg ikke sjekket

**Comment by KurtStian** [comment]
eurovoc vises ikke for datasett (dcat:theme), og verken eurovoc eller los vises for tjeneste (cv:thematicArea) i portalen.

**Comment by NilsOveTen** [comment]
Ja, for alt som legges til her blir ignorert av fdk-rdf-parser. Vi må først og fremst fikse ting der. Men det blir veldig kaotisk om den skal ta noe data herfra og annet fra reference-data. Så mener vi må flytte alt som har med tema fra reference-data inn hit, og kun forholde oss til tripler fra reasoning.service i fdk-rdf-parser

**Comment by terjesyl** [comment]
Veldig for dette, at rdf-parseren kun er en parser og ikke extender/utvider grafene. Per nå gjør jo parserern også en slags reasoning.

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/fdk-reasoning-service/commit/a025b53aadefd78966f8d06b950a95d1dec1fb59
