### ISSUE TITLE
Legg til fjernede ressurser i ReasoningResponse

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-reasoning-service#73]
rdf-parser-tjenesten trenger å vite om ressurser som har blitt fjernet.

Legg til feltet `val removedResources: List<FdkIdAndUri> = emptyList()` i ReasonsResponse-modellen.

**Comment by terjesyl** [comment]
Denne kan vel lukkes nå, eller? @NilsOveTen

**Comment by NilsOveTen** [comment]
Er ikke nødvendig
